import type {
  FocusedTrainingRuntimeDelegateArgs,
  UseFocusedTrainingRuntimeArgs,
} from '../focusedTrainingRuntimeDelegateTypes';

export function buildFocusedTrainingActiveSessionSyncArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['activeSessionSync'] {
  return {
    sessions: args.sessions,
    setSessions: args.setSessions,
    activeSession: args.activeSession,
    activeSessionId: args.activeSessionId,
    difficulty: args.difficulty,
    inputSettingsLocked: args.inputSettingsLocked,
    ttsText: args.ttsText,
    ttsLanguage: args.ttsLanguage,
    ttsPracticeText: args.ttsPracticeText,
    sessionStatus: args.sessionStatus,
    controllerState: args.controllerState,
    running: args.running,
    rate: args.rate,
    lagSec: args.lagSec,
    lagWords: args.lagWords,
    wpm: args.wpm,
    accuracy: args.accuracy,
    trend: args.trend,
    hydratingSessionIdRef: args.hydratingSessionIdRef,
    allowFinishedSessionResetRef: args.allowFinishedSessionResetRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    ttsUiLastPublishedAtRef: args.ttsUiLastPublishedAtRef,
    ttsPublishedUiRef: args.ttsPublishedUiRef,
    telemetryRef: args.telemetryRef,
    previousLagRef: args.previousLagRef,
    previousAccuracyRef: args.previousAccuracyRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsChunkStartMsRef: args.ttsChunkStartMsRef,
    ttsChunkStartWordIndexRef: args.ttsChunkStartWordIndexRef,
    ttsChunkWordCountRef: args.ttsChunkWordCountRef,
    ttsCompletedSourceWordsRef: args.ttsCompletedSourceWordsRef,
    ttsLagOutlierCountRef: args.ttsLagOutlierCountRef,
    ttsUnsafeChunkCountRef: args.ttsUnsafeChunkCountRef,
    ttsChunkAccuracyWindowRef: args.ttsChunkAccuracyWindowRef,
    ttsLastAccuracySnapshotRef: args.ttsLastAccuracySnapshotRef,
    ttsLastControllerActionRef: args.ttsLastControllerActionRef,
    setDifficulty: args.setDifficulty,
    setInputSettingsLocked: args.setInputSettingsLocked,
    setTtsLanguage: args.setTtsLanguage,
    setTtsPracticeText: args.setTtsPracticeText,
    setSessionStatus: args.setSessionStatus,
    setTtsText: args.setTtsText,
    setTtsStatus: args.setTtsStatus,
    setTtsCurrentChunk: args.setTtsCurrentChunk,
    setTtsPacingMode: args.setTtsPacingMode,
    setTtsSpeechRate: args.setTtsSpeechRate,
    setRunning: args.setRunning,
    setRate: args.setRate,
    setLagSec: args.setLagSec,
    setLagWords: args.setLagWords,
    setWpm: args.setWpm,
    setAccuracy: args.setAccuracy,
    setTrend: args.setTrend,
    setControllerState: args.setControllerState,
    setExportMessage: args.setExportMessage,
    setError: args.setError,
    setTrainingSubmitMessage: args.setTrainingSubmitMessage,
    resetAdaptiveSessionFeedbackTracking: args.resetAdaptiveSessionFeedbackTracking,
  };
}
