import type {
  FocusedTrainingRuntimeDelegateArgs,
  UseFocusedTrainingRuntimeArgs,
} from '../focusedTrainingRuntimeDelegateTypes';

export function buildFocusedTrainingRouteArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['focusedRoute'] {
  return {
    activeInputMode: args.activeInputMode,
    activeSession: args.activeSession,
    activeTrainingSubmissionMeta: args.activeTrainingSubmissionMeta,
    activeInputLabel: args.activeInputLabel,
    sessionStatus: args.sessionStatus,
    ttsStatus: args.ttsStatus,
    running: args.running,
    inputSettingsLocked: args.inputSettingsLocked,
    lagSec: args.lagSec,
    activeSessionFinished: args.activeSessionFinished,
    error: args.error,
    trainingSubmitMessage: args.trainingSubmitMessage,
    exportMessage: args.exportMessage,
    openRouterJobStatus: args.openRouterJobStatus,
    openRouterError: args.openRouterError,
    ttsSpeechRate: args.ttsSpeechRate,
    ttsLanguage: args.ttsLanguage,
    adaptiveSemanticDebug: args.adaptiveSemanticDebug,
    ttsPracticeText: args.ttsPracticeText,
    ttsPlayerProgressTick: args.ttsPlayerProgressTick,
    setInputSettingsLocked: args.setInputSettingsLocked,
    setError: args.setError,
    setExportMessage: args.setExportMessage,
    telemetryRef: args.telemetryRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    pendingSessions: args.pendingSessions,
    activeSessionId: args.activeSessionId,
    openWorkspaceForSession: args.openWorkspaceForSession,
    deleteSession: args.deleteSession,
    supabaseSyncStatus: args.supabaseSyncStatus,
    pendingSyncSummary: args.pendingSyncSummary,
    openRouterAccessAllowed: args.openRouterAccessAllowed,
    isOnline: args.isOnline,
    effectiveOpenRouterDefaultModel: args.effectiveOpenRouterDefaultModel,
    sessionQuotaStatus: args.sessionQuotaStatus,
    openRouterOfflineTitle: args.openRouterOfflineTitle,
    activeOpenRouterJobs: args.activeOpenRouterJobs,
    openRouterJobNotifications: args.openRouterJobNotifications,
    trainingGenerationNotices: args.trainingGenerationNotices,
    trainingGenerationNowMs: args.trainingGenerationNowMs,
    directOpenRouterBusy: args.directOpenRouterBusy,
    generateAdaptiveNextSessionFromOpenRouter: args.generateAdaptiveNextSessionFromOpenRouter,
  };
}
