import type { useAdaptiveWorkspaceRouteRuntime } from './useAdaptiveWorkspaceRouteRuntime';
import type { DictaAppRouteCompositionRuntimeParams } from './dictaAppRouteCompositionTypes';

type AdaptiveWorkspaceRouteRuntimeInput = Parameters<typeof useAdaptiveWorkspaceRouteRuntime>[0];

export function buildAdaptiveWorkspaceRouteRuntimeInput({
  adaptiveBenchmarksByInputLanguage,
  adaptiveSessionFeedbackByInputLanguage,
  adaptiveBenchmarksFocusAnchor,
  selectedBenchmarkInputMode,
  selectedBenchmarkLanguage,
  insightsDiagnosticInputMode,
  metricsLanguageView,
  latestSession,
  sessions,
  activeSession,
  activeSessionFinished,
  sessionStatus,
  getActiveTypingLanguage,
  setBenchmarkExportMessage,
  setExportMessage,
  setSessionFeedbackMessage,
  setInsightsDiagnosticFallbackReport,
  setInsightsDiagnosticMessage,
  adaptiveSectionExpanded,
  adaptiveSemanticDebug,
  setAdaptiveSectionExpanded,
  setSelectedBenchmarkInputMode,
  setSelectedBenchmarkLanguage,
  benchmarkExportMessage,
  sessionFeedbackMessage,
  formatSessionDate,
}: DictaAppRouteCompositionRuntimeParams): AdaptiveWorkspaceRouteRuntimeInput {
  return {
    presentation: {
      adaptiveBenchmarksByInputLanguage,
      adaptiveSessionFeedbackByInputLanguage,
      selectedBenchmarkInputMode,
      selectedBenchmarkLanguage,
      insightsDiagnosticInputMode,
      metricsLanguageView,
      latestSession,
    },
    exportActions: {
      sessions,
      activeSession,
      activeSessionFinished,
      sessionStatus,
      getActiveTypingLanguage,
      insightsDiagnosticInputMode,
      metricsLanguageView,
      setBenchmarkExportMessage,
      setExportMessage,
      setSessionFeedbackMessage,
      setInsightsDiagnosticFallbackReport,
      setInsightsDiagnosticMessage,
    },
    diagnostics: {
      adaptiveSectionExpanded,
      latestSession,
      adaptiveSemanticDebug,
      setAdaptiveSectionExpanded,
    },
    benchmark: {
      adaptiveBenchmarksByInputLanguage,
      adaptiveSectionExpanded,
      adaptiveBenchmarksFocusAnchor,
      selectedBenchmarkInputMode,
      selectedBenchmarkLanguage,
      benchmarkExportMessage,
      sessionFeedbackMessage,
      formatSessionDate,
      setAdaptiveSectionExpanded,
      setSelectedBenchmarkInputMode,
      setSelectedBenchmarkLanguage,
      setBenchmarkExportMessage,
      setSessionFeedbackMessage,
    },
  };
}
