import type {
  FocusedTrainingRuntimeDelegateArgs,
  UseFocusedTrainingRuntimeArgs,
} from './focusedTrainingRuntimeDelegateTypes';

export function buildFocusedTrainingLiveMetricsArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['liveMetrics'] {
  return {
    activeInputMode: args.activeInputMode,
    ttsText: args.ttsText,
    ttsPracticeText: args.ttsPracticeText,
    lagSec: args.lagSec,
    wpm: args.wpm,
    rate: args.rate,
  };
}

export function buildFocusedTrainingPlaybackIntervalsArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['playbackIntervals'] {
  return {
    activeInputMode: args.activeInputMode,
    activeSessionFinished: args.activeSessionFinished,
    ttsStatus: args.ttsStatus,
    applyTtsPerformanceSampleRef: args.applyTtsPerformanceSampleRef,
    setTtsPlayerProgressTick: args.setTtsPlayerProgressTick,
  };
}

export function buildFocusedTrainingActiveSessionSyncArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['activeSessionSync'] {
  return {
    sessions: args.sessions,
    setSessions: args.setSessions,
    activeSession: args.activeSession,
    activeSessionId: args.activeSessionId,
    difficulty: args.difficulty,
    inputSettingsLocked: args.inputSettingsLocked,
    ttsText: args.ttsText,
    ttsLanguage: args.ttsLanguage,
    ttsPracticeText: args.ttsPracticeText,
    sessionStatus: args.sessionStatus,
    controllerState: args.controllerState,
    running: args.running,
    rate: args.rate,
    lagSec: args.lagSec,
    lagWords: args.lagWords,
    wpm: args.wpm,
    accuracy: args.accuracy,
    trend: args.trend,
    hydratingSessionIdRef: args.hydratingSessionIdRef,
    allowFinishedSessionResetRef: args.allowFinishedSessionResetRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    ttsUiLastPublishedAtRef: args.ttsUiLastPublishedAtRef,
    ttsPublishedUiRef: args.ttsPublishedUiRef,
    telemetryRef: args.telemetryRef,
    previousLagRef: args.previousLagRef,
    previousAccuracyRef: args.previousAccuracyRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsChunkStartMsRef: args.ttsChunkStartMsRef,
    ttsChunkStartWordIndexRef: args.ttsChunkStartWordIndexRef,
    ttsChunkWordCountRef: args.ttsChunkWordCountRef,
    ttsCompletedSourceWordsRef: args.ttsCompletedSourceWordsRef,
    ttsLagOutlierCountRef: args.ttsLagOutlierCountRef,
    ttsUnsafeChunkCountRef: args.ttsUnsafeChunkCountRef,
    ttsChunkAccuracyWindowRef: args.ttsChunkAccuracyWindowRef,
    ttsLastAccuracySnapshotRef: args.ttsLastAccuracySnapshotRef,
    ttsLastControllerActionRef: args.ttsLastControllerActionRef,
    setDifficulty: args.setDifficulty,
    setInputSettingsLocked: args.setInputSettingsLocked,
    setTtsLanguage: args.setTtsLanguage,
    setTtsPracticeText: args.setTtsPracticeText,
    setSessionStatus: args.setSessionStatus,
    setTtsText: args.setTtsText,
    setTtsStatus: args.setTtsStatus,
    setTtsCurrentChunk: args.setTtsCurrentChunk,
    setTtsPacingMode: args.setTtsPacingMode,
    setTtsSpeechRate: args.setTtsSpeechRate,
    setRunning: args.setRunning,
    setRate: args.setRate,
    setLagSec: args.setLagSec,
    setLagWords: args.setLagWords,
    setWpm: args.setWpm,
    setAccuracy: args.setAccuracy,
    setTrend: args.setTrend,
    setControllerState: args.setControllerState,
    setExportMessage: args.setExportMessage,
    setError: args.setError,
    setTrainingSubmitMessage: args.setTrainingSubmitMessage,
    resetAdaptiveSessionFeedbackTracking: args.resetAdaptiveSessionFeedbackTracking,
  };
}

export function buildFocusedTrainingTtsOrchestrationArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['ttsOrchestration'] {
  return {
    activeInputMode: args.activeInputMode,
    inputSettingsLocked: args.inputSettingsLocked,
    ttsLanguage: args.ttsLanguage,
    activeSessionFinished: args.activeSessionFinished,
    telemetryRef: args.telemetryRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    setTtsPracticeText: args.setTtsPracticeText,
    ttsStatus: args.ttsStatus,
    ttsSpeechRate: args.ttsSpeechRate,
    controllerState: args.controllerState,
    rate: args.rate,
    lagSec: args.lagSec,
    lagWords: args.lagWords,
    wpm: args.wpm,
    accuracy: args.accuracy,
    trend: args.trend,
    ttsChunkStartMsRef: args.ttsChunkStartMsRef,
    ttsChunkWordCountRef: args.ttsChunkWordCountRef,
    ttsChunkStartWordIndexRef: args.ttsChunkStartWordIndexRef,
    ttsCompletedSourceWordsRef: args.ttsCompletedSourceWordsRef,
    ttsLastValidControlLagSecRef: args.ttsLastValidControlLagSecRef,
    ttsLagOutlierCountRef: args.ttsLagOutlierCountRef,
    ttsLiveSignalRef: args.ttsLiveSignalRef,
    previousLagRef: args.previousLagRef,
    previousAccuracyRef: args.previousAccuracyRef,
    ttsLastControllerActionRef: args.ttsLastControllerActionRef,
    ttsPublishedUiRef: args.ttsPublishedUiRef,
    ttsUiLastPublishedAtRef: args.ttsUiLastPublishedAtRef,
    applyTtsPerformanceSampleRef: args.applyTtsPerformanceSampleRef,
    setControllerState: args.setControllerState,
    setRate: args.setRate,
    setLagSec: args.setLagSec,
    setLagWords: args.setLagWords,
    setWpm: args.setWpm,
    setAccuracy: args.setAccuracy,
    setTrend: args.setTrend,
    activeSession: args.activeSession,
    ttsText: args.ttsText,
    ttsPacingMode: args.ttsPacingMode,
    browserTtsVoices: args.browserTtsVoices,
    ttsPlaybackProfile: args.ttsPlaybackProfile,
    perfDiagnostics: args.perfDiagnostics,
    stopTtsPlaybackRef: args.stopTtsPlaybackRef,
    ttsPausedAtWordIndexRef: args.ttsPausedAtWordIndexRef,
    ttsUnsafeChunkCountRef: args.ttsUnsafeChunkCountRef,
    ttsChunkAccuracyWindowRef: args.ttsChunkAccuracyWindowRef,
    ttsLastAccuracySnapshotRef: args.ttsLastAccuracySnapshotRef,
    ttsUtteranceRef: args.ttsUtteranceRef,
    ttsSemanticPhraseAdvanceCountRef: args.ttsSemanticPhraseAdvanceCountRef,
    ttsSemanticPhraseReplayCountRef: args.ttsSemanticPhraseReplayCountRef,
    isBrowserTtsSupported: args.isBrowserTtsSupported,
    speakBrowserTts: args.speakBrowserTts,
    resolveActiveBrowserTtsVoice: args.resolveActiveBrowserTtsVoice,
    collectBrowserTtsEnvironmentForSession: args.collectBrowserTtsEnvironmentForSession,
    getHistoricalPerformanceProfile: args.getHistoricalPerformanceProfile,
    getBenchmarkSnapshot: args.getBenchmarkSnapshot,
    getAdaptiveController: args.getAdaptiveController,
    beginAdaptiveSessionFeedback: args.beginAdaptiveSessionFeedback,
    recordPhrasePlaybackEvent: args.recordPhrasePlaybackEvent,
    recordAdaptiveBenchmark: args.recordAdaptiveBenchmark,
    setAdaptiveSemanticDebug: args.setAdaptiveSemanticDebug,
    setTtsCurrentChunk: args.setTtsCurrentChunk,
    setTtsPacingMode: args.setTtsPacingMode,
    setTtsSpeechRate: args.setTtsSpeechRate,
    setTtsStatus: args.setTtsStatus,
    setRunning: args.setRunning,
    setSessionStatus: args.setSessionStatus,
    setError: args.setError,
    ttsPracticeText: args.ttsPracticeText,
    cancelBrowserTts: args.cancelBrowserTts,
    resumeBrowserTts: args.resumeBrowserTts,
    setTtsPlayerProgressTick: args.setTtsPlayerProgressTick,
    resetAdaptiveSessionFeedbackTracking: args.resetAdaptiveSessionFeedbackTracking,
    allowFinishedSessionResetRef: args.allowFinishedSessionResetRef,
    setTrainingSubmitMessage: args.setTrainingSubmitMessage,
    setInputSettingsLocked: args.setInputSettingsLocked,
    sessions: args.sessions,
    activeSessionId: args.activeSessionId,
    resolveBrowserTtsVoiceForSession: args.resolveBrowserTtsVoiceForSession,
    persistAndPushSessionsNow: args.persistAndPushSessionsNow,
    completeAdaptiveSessionFeedback: args.completeAdaptiveSessionFeedback,
    setSessions: args.setSessions,
  };
}

export function buildFocusedTrainingRouteArgs(
  args: UseFocusedTrainingRuntimeArgs,
): FocusedTrainingRuntimeDelegateArgs['focusedRoute'] {
  return {
    activeInputMode: args.activeInputMode,
    activeSession: args.activeSession,
    activeTrainingSubmissionMeta: args.activeTrainingSubmissionMeta,
    activeInputLabel: args.activeInputLabel,
    sessionStatus: args.sessionStatus,
    ttsStatus: args.ttsStatus,
    running: args.running,
    inputSettingsLocked: args.inputSettingsLocked,
    lagSec: args.lagSec,
    activeSessionFinished: args.activeSessionFinished,
    error: args.error,
    trainingSubmitMessage: args.trainingSubmitMessage,
    exportMessage: args.exportMessage,
    openRouterJobStatus: args.openRouterJobStatus,
    openRouterError: args.openRouterError,
    ttsSpeechRate: args.ttsSpeechRate,
    ttsLanguage: args.ttsLanguage,
    adaptiveSemanticDebug: args.adaptiveSemanticDebug,
    ttsPracticeText: args.ttsPracticeText,
    ttsPlayerProgressTick: args.ttsPlayerProgressTick,
    setInputSettingsLocked: args.setInputSettingsLocked,
    setError: args.setError,
    setExportMessage: args.setExportMessage,
    telemetryRef: args.telemetryRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    pendingSessions: args.pendingSessions,
    activeSessionId: args.activeSessionId,
    openWorkspaceForSession: args.openWorkspaceForSession,
    deleteSession: args.deleteSession,
    supabaseSyncStatus: args.supabaseSyncStatus,
    pendingSyncSummary: args.pendingSyncSummary,
    openRouterAccessAllowed: args.openRouterAccessAllowed,
    isOnline: args.isOnline,
    effectiveOpenRouterDefaultModel: args.effectiveOpenRouterDefaultModel,
    sessionQuotaStatus: args.sessionQuotaStatus,
    openRouterOfflineTitle: args.openRouterOfflineTitle,
    activeOpenRouterJobs: args.activeOpenRouterJobs,
    openRouterJobNotifications: args.openRouterJobNotifications,
    trainingGenerationNotices: args.trainingGenerationNotices,
    trainingGenerationNowMs: args.trainingGenerationNowMs,
    directOpenRouterBusy: args.directOpenRouterBusy,
    directIntermediateOpenRouterBusy: args.directIntermediateOpenRouterBusy,
    directAdvancedOpenRouterBusy: args.directAdvancedOpenRouterBusy,
    generateEasyNextSessionFromOpenRouter: args.generateEasyNextSessionFromOpenRouter,
    generateIntermediateNextSessionFromOpenRouter: args.generateIntermediateNextSessionFromOpenRouter,
    generateAdvancedNextSessionFromOpenRouter: args.generateAdvancedNextSessionFromOpenRouter,
  };
}
