import type { DependencyList } from 'react';
import type { TtsPlaybackMetricsRuntimeOptions } from './useTtsPlaybackMetricsRuntimeTypes';

export function getTtsPlaybackMetricsRuntimeMemoDeps(
  options: TtsPlaybackMetricsRuntimeOptions,
): DependencyList {
  return [
    options.accuracy,
    options.applyTtsPerformanceSampleRef,
    options.baseWordsPerSecond,
    options.controllerState,
    options.lagSec,
    options.lagWords,
    options.minPublishIntervalMs,
    options.nowIso,
    options.nowMs,
    options.previousAccuracyRef,
    options.previousLagRef,
    options.rate,
    options.setAccuracy,
    options.setControllerState,
    options.setLagSec,
    options.setLagWords,
    options.setRate,
    options.setTrend,
    options.setWpm,
    options.telemetryRef,
    options.trend,
    options.ttsChunkStartMsRef,
    options.ttsChunkStartWordIndexRef,
    options.ttsChunkWordCountRef,
    options.ttsCompletedSourceWordsRef,
    options.ttsLagOutlierCountRef,
    options.ttsLanguage,
    options.ttsLastControllerActionRef,
    options.ttsLastValidControlLagSecRef,
    options.ttsLiveSignalRef,
    options.ttsPracticeLiveTextRef,
    options.ttsPublishedUiRef,
    options.ttsSpeechRate,
    options.ttsStartedAtMsRef,
    options.ttsStatus,
    options.ttsTranscript,
    options.ttsUiLastPublishedAtRef,
    options.wpm,
  ];
}
