import { useMemo } from 'react';
import {
  invokeBenchmarkHandler,
  toggleAdaptiveBenchmarkExpanded,
} from './adaptiveBenchmarkSectionPropsHandlers';
import type {
  AdaptiveBenchmarkSectionProps,
  UseAdaptiveBenchmarkSectionPropsArgs,
} from './adaptiveBenchmarkSectionPropsTypes';

export function useAdaptiveBenchmarkSectionProps<TAdaptiveSectionExpanded extends { benchmarks: boolean }>({
  adaptiveAdapters,
  adaptiveBenchmarksByInputLanguage,
  adaptiveSectionExpanded,
  adaptiveBenchmarksFocusAnchor,
  selectedBenchmarkInputMode,
  selectedBenchmarkLanguage,
  selectedBenchmarkProfile,
  repeatWordStats,
  benchmarkExportMessage,
  selectedSessionFeedback,
  sessionFeedbackMessage,
  formatSessionDate,
  setAdaptiveSectionExpanded,
  setSelectedBenchmarkInputMode,
  setSelectedBenchmarkLanguage,
  setBenchmarkExportMessage,
  setSessionFeedbackMessage,
  copySelectedBenchmarkJson,
  downloadSelectedBenchmarkJson,
  copyDictationScriptPrompt,
  copyBenchmarkWithDictationScriptPrompt,
  copyDictationScriptTemplate,
  copySessionFeedbackJson,
  copyBenchmarkFeedbackJson,
  copyBenchmarkFeedbackPrompt,
  copyBenchmarkFeedbackPromptWithHumanFeedback,
}: UseAdaptiveBenchmarkSectionPropsArgs<TAdaptiveSectionExpanded>): AdaptiveBenchmarkSectionProps {
  return useMemo(
    () => ({
      id: 'adaptive-benchmarks',
      adapters: adaptiveAdapters,
      benchmarks: adaptiveBenchmarksByInputLanguage,
      expanded: adaptiveSectionExpanded.benchmarks,
      onToggleExpanded: () => toggleAdaptiveBenchmarkExpanded(setAdaptiveSectionExpanded),
      focusAnchor: adaptiveBenchmarksFocusAnchor,
      selectedInputMode: selectedBenchmarkInputMode,
      selectedLanguage: selectedBenchmarkLanguage,
      selectedProfile: selectedBenchmarkProfile,
      repeatWordStats,
      formatSessionDate,
      onSelect: (inputMode, language) => {
        setSelectedBenchmarkInputMode(inputMode);
        setSelectedBenchmarkLanguage(language);
        setBenchmarkExportMessage('');
        setSessionFeedbackMessage('');
      },
      benchmarkExportMessage,
      sessionFeedback: selectedSessionFeedback,
      sessionFeedbackMessage,
      onCopyBenchmark: (profile) => invokeBenchmarkHandler(copySelectedBenchmarkJson, profile),
      onExportBenchmark: (profile) => invokeBenchmarkHandler(downloadSelectedBenchmarkJson, profile),
      onCopyScriptPrompt: (profile) => invokeBenchmarkHandler(copyDictationScriptPrompt, profile),
      onCopyBenchmarkWithScriptPrompt: (profile) => invokeBenchmarkHandler(copyBenchmarkWithDictationScriptPrompt, profile),
      onCopyScriptTemplate: (profile) => invokeBenchmarkHandler(copyDictationScriptTemplate, profile),
      onCopySessionFeedback: (profile, feedback) => invokeBenchmarkHandler(copySessionFeedbackJson, profile, feedback),
      onCopyBenchmarkFeedback: (profile, feedback) => invokeBenchmarkHandler(copyBenchmarkFeedbackJson, profile, feedback),
      onCopyBenchmarkFeedbackPrompt: (profile, feedback) => invokeBenchmarkHandler(copyBenchmarkFeedbackPrompt, profile, feedback),
      onCopyBenchmarkFeedbackPromptWithHumanFeedback: (profile, feedback, humanFeedback) =>
        invokeBenchmarkHandler(copyBenchmarkFeedbackPromptWithHumanFeedback, profile, feedback, humanFeedback),
    }),
    [
      adaptiveAdapters,
      adaptiveBenchmarksByInputLanguage,
      adaptiveSectionExpanded.benchmarks,
      adaptiveBenchmarksFocusAnchor,
      selectedBenchmarkInputMode,
      selectedBenchmarkLanguage,
      selectedBenchmarkProfile,
      repeatWordStats,
      formatSessionDate,
      benchmarkExportMessage,
      selectedSessionFeedback,
      sessionFeedbackMessage,
      setAdaptiveSectionExpanded,
      setSelectedBenchmarkInputMode,
      setSelectedBenchmarkLanguage,
      setBenchmarkExportMessage,
      setSessionFeedbackMessage,
      copySelectedBenchmarkJson,
      downloadSelectedBenchmarkJson,
      copyDictationScriptPrompt,
      copyBenchmarkWithDictationScriptPrompt,
      copyDictationScriptTemplate,
      copySessionFeedbackJson,
      copyBenchmarkFeedbackJson,
      copyBenchmarkFeedbackPrompt,
      copyBenchmarkFeedbackPromptWithHumanFeedback,
    ],
  );
}
