import { useMemo } from 'react';
import type { BrowserTtsSetupCardProps } from '../components/runtime-workspaces/BrowserTtsSetupCard';

export function useBrowserTtsSetupCardProps({
  activeInputLabel,
  activeInputFeatureLabel,
  ttsExpanded,
  ttsHasText,
  ttsText,
  ttsLanguage,
  ttsStatus,
  ttsSpeechRate,
  ttsPacingMode,
  ttsCurrentChunk,
  supportedLanguages,
  setupLocked,
  inputSettingsReady,
  onToggleExpanded,
  onTtsTextChange,
  onTtsLanguageChange,
  onLockInputSettings,
  formatTtsPacingMode,
}: BrowserTtsSetupCardProps): BrowserTtsSetupCardProps {
  return useMemo(() => ({
    activeInputLabel,
    activeInputFeatureLabel,
    ttsExpanded,
    ttsHasText,
    ttsText,
    ttsLanguage,
    ttsStatus,
    ttsSpeechRate,
    ttsPacingMode,
    ttsCurrentChunk,
    supportedLanguages,
    setupLocked,
    inputSettingsReady,
    onToggleExpanded,
    onTtsTextChange,
    onTtsLanguageChange,
    onLockInputSettings,
    formatTtsPacingMode,
  }), [
    activeInputLabel,
    activeInputFeatureLabel,
    ttsExpanded,
    ttsHasText,
    ttsText,
    ttsLanguage,
    ttsStatus,
    ttsSpeechRate,
    ttsPacingMode,
    ttsCurrentChunk,
    supportedLanguages,
    setupLocked,
    inputSettingsReady,
    onToggleExpanded,
    onTtsTextChange,
    onTtsLanguageChange,
    onLockInputSettings,
    formatTtsPacingMode,
  ]);
}
