import { useDictaLocalStorageImportRuntime } from './useDictaLocalStorageImportRuntime';
import { useDictaRootRouteCompositionRuntime } from './useDictaRootRouteCompositionRuntime';
import type { DictaRuntimeRootAdaptiveWorkspaceGraph } from './useDictaRuntimeRootAdaptiveWorkspaceGraph';
import type { DictaRuntimeRootEnvironment } from './useDictaRuntimeRootEnvironment';
import type { DictaRuntimeRootFocusedTrainingGraph } from './useDictaRuntimeRootFocusedTrainingGraph';
import type { DictaRuntimeRootOpenRouterGraph } from './useDictaRuntimeRootOpenRouterGraph';
import type { DictaRuntimeRootSessionGraph } from './useDictaRuntimeRootSessionGraph';
import { formatSessionDate } from './sessionDateFormatters';
import { formatSessionPlaybackDuration } from './sessionPlaybackDuration';
import { formatSessionStatus } from './sessionStatusFormatters';

type UseDictaRuntimeRootPresentationGraphOptions = {
  environment: DictaRuntimeRootEnvironment;
  sessionGraph: DictaRuntimeRootSessionGraph;
  adaptiveWorkspaceGraph: DictaRuntimeRootAdaptiveWorkspaceGraph;
  openRouterGraph: DictaRuntimeRootOpenRouterGraph;
  focusedTrainingGraph: DictaRuntimeRootFocusedTrainingGraph;
  localDevFeaturesAvailable: boolean;
};

export function useDictaRuntimeRootPresentationGraph({
  environment,
  sessionGraph,
  adaptiveWorkspaceGraph,
  openRouterGraph,
  focusedTrainingGraph,
  localDevFeaturesAvailable,
}: UseDictaRuntimeRootPresentationGraphOptions) {
  const {
    perfDiagnosticsEnabled,
    sessionsState,
    trainingState,
    routing,
    theme,
    accessRuntime,
    uiPreferences,
    adaptiveWorkspaceState,
  } = environment;
  const {
    sessions,
    setSessions,
    activeSessionId,
    setActiveSessionId,
  } = sessionsState;
  const {
    sessionStatus,
    exportMessage,
    setExportMessage,
    ttsStatus,
    ttsCurrentChunk,
    ttsPacingMode,
    trend,
  } = trainingState;
  const {
    workspaceMode,
    currentPath,
    navigateAppRoute,
    showLeaderboardWorkspace,
    showAdminWorkspace,
    showOpenRouterWorkspace,
    clearDashboardSession,
  } = routing;
  const { themeMode, setThemeMode } = theme;
  const {
    syncConfig,
    authSession,
    authLoading,
    authEmail,
    setAuthEmail,
    authPassword,
    setAuthPassword,
    authError,
    authView,
    authNewPassword,
    setAuthNewPassword,
    authNewPasswordConfirm,
    setAuthNewPasswordConfirm,
    authMessage,
    authMessageTone,
    authBusy,
    appProfile,
    appProfileError,
    openRouterAccessState,
    openRouterAccessAllowed,
    openRouterAccessMessage,
    visibleProfiles,
    adminProfileFilter,
    setAdminProfileFilter,
    adminRemoteStatus,
    effectiveProfileId,
    isCurrentProfileAdmin,
    signInWithSupabase,
    showAuthView,
    requestSupabasePasswordReset,
    updateSupabasePassword,
    signOut,
    getAuthHeaders,
    setOpenRouterDefaultModel,
    openRouterModels,
    openRouterStatus,
    openRouterError,
    assignedOpenRouterModel,
    effectiveOpenRouterDefaultModel,
    refreshOpenRouterModels,
    adminFileInventory,
    adminFileInventoryError,
    updateAdminProfileAccess,
    adminProfileSessionCounts,
  } = accessRuntime;
  const {
    dictaLanguageView,
    setDictaLanguageView,
    metricsLanguageView,
    leaderboardLanguageView,
    adminLanguageView,
    setMetricsLanguageView,
    setLeaderboardLanguageView,
    setAdminLanguageView,
    insightsCollapsed,
    setInsightsCollapsed,
    leaderboardExpanded,
    setLeaderboardExpanded,
    leaderboardSectionExpanded,
    setLeaderboardSectionExpanded,
    metricsRangeView,
    setMetricsRangeView,
    adaptiveSectionExpanded,
    setAdaptiveSectionExpanded,
  } = uiPreferences;
  const {
    adaptiveSemanticDebug,
    adaptiveBenchmarksByInputLanguage,
    setAdaptiveBenchmarksByInputLanguage,
    adaptiveSessionFeedbackByInputLanguage,
    setAdaptiveSessionFeedbackByInputLanguage,
    adaptiveBenchmarksFocusAnchor,
    benchmarkExportMessage,
    setBenchmarkExportMessage,
    sessionFeedbackMessage,
    setSessionFeedbackMessage,
  } = adaptiveWorkspaceState;
  const {
    persistenceRuntime,
    sessionCreationRuntime,
    ttsSessionRuntime,
  } = sessionGraph;
  const {
    localStorageReadyForEffectiveProfile,
    supabaseInitialSyncPending,
    supabaseSyncStatus,
    sessionQuotaStatus,
  } = persistenceRuntime;
  const {
    sessionCreationMode,
    sessionCreationSource,
    changeSessionCreationSource,
    sessionCreationName,
    setSessionCreationName,
    dictationScriptJson,
    changeDictationScriptJson,
    dictationScriptValidation,
    cancelSessionCreation,
    createSessionWithMode,
    validateScriptImport,
    createSessionFromDictationScript,
  } = sessionCreationRuntime;
  const {
    activeSession,
    dashboardSession,
    activeSessionFinished,
  } = ttsSessionRuntime;
  const {
    adaptiveRuntime,
    workspaceSessionRuntime,
  } = adaptiveWorkspaceGraph;
  const {
    insightsDiagnosticInputMode,
    setInsightsDiagnosticInputMode,
    insightsDiagnosticMessage,
    setInsightsDiagnosticMessage,
    insightsDiagnosticFallbackReport,
    setInsightsDiagnosticFallbackReport,
    setSelectedBenchmarkInputMode,
    setSelectedBenchmarkLanguage,
    openAdaptiveExportsForActiveInput,
    openAdaptiveWorkspaceFromHeader,
  } = adaptiveRuntime;
  const {
    latestSession,
    pendingSessions,
    pendingSyncSummary,
    leaderboard,
    leaderboardSections,
    adminSessions,
    adminStorageSummary,
    lastSessionForLanguage,
    lastSessionScoreHelpText,
    languageTodaySummary,
    deleteSession,
    openDashboardForSession,
    openWorkspaceForSession,
  } = workspaceSessionRuntime;
  const {
    focusedTrainingProps,
    getActiveTypingLanguage,
  } = focusedTrainingGraph;

  const { importDictaLocalStorageSnapshot } = useDictaLocalStorageImportRuntime({
    setSessions,
    setActiveSessionId,
    clearDashboardSession,
    setAdaptiveBenchmarksByInputLanguage,
    setAdaptiveSessionFeedbackByInputLanguage,
    setDictaLanguageView,
    setOpenRouterDefaultModel,
    showLeaderboardWorkspace,
    setExportMessage,
  });

  const routeCompositionRuntime = useDictaRootRouteCompositionRuntime({
    adaptiveBenchmarksByInputLanguage,
    adaptiveSessionFeedbackByInputLanguage,
    adaptiveBenchmarksFocusAnchor,
    selectedBenchmarkInputMode: openRouterGraph.selectedBenchmarkInputMode,
    selectedBenchmarkLanguage: openRouterGraph.selectedBenchmarkLanguage,
    insightsDiagnosticInputMode,
    metricsLanguageView,
    latestSession,
    sessions,
    activeSession,
    activeSessionFinished,
    sessionStatus,
    getActiveTypingLanguage,
    setBenchmarkExportMessage,
    setExportMessage,
    setSessionFeedbackMessage,
    setInsightsDiagnosticFallbackReport,
    setInsightsDiagnosticMessage,
    adaptiveSectionExpanded,
    adaptiveSemanticDebug,
    setAdaptiveSectionExpanded,
    setSelectedBenchmarkInputMode,
    setSelectedBenchmarkLanguage,
    benchmarkExportMessage,
    sessionFeedbackMessage,
    formatSessionDate,
    currentPath,
    openAdaptiveExportsForActiveInput,
    effectiveOpenRouterDefaultModel,
    assignedOpenRouterModel,
    getAuthHeaders,
    setOpenRouterDefaultModel,
    openRouterModels,
    openRouterStatus,
    openRouterError,
    refreshOpenRouterModels,
    showLeaderboardWorkspace,
    openRouterGenerateFocusRequest: openRouterGraph.openRouterGenerateFocusRequest,
    activeOpenRouterJobs: openRouterGraph.activeOpenRouterJobs,
    openRouterJobNotifications: openRouterGraph.openRouterJobNotifications,
    trainingGenerationNowMs: openRouterGraph.trainingGenerationNowMs,
    trackOpenRouterJob: openRouterGraph.trackOpenRouterJob,
    createOpenRouterErrorSession: openRouterGraph.createOpenRouterErrorSession,
    adminSessions,
    adminStorageSummary,
    adminFileInventory,
    adminFileInventoryError,
    exportMessage,
    supabaseSyncStatus,
    adminLanguageView,
    setAdminLanguageView,
    importDictaLocalStorageSnapshot,
    appProfile,
    visibleProfiles,
    adminProfileSessionCounts,
    adminProfileFilter,
    setAdminProfileFilter,
    updateAdminProfileAccess,
    adminRemoteStatus,
    leaderboard,
    leaderboardSections,
    leaderboardLanguageView,
    leaderboardExpanded,
    leaderboardSectionExpanded,
    activeSessionId,
    setLeaderboardLanguageView,
    setLeaderboardExpanded,
    setLeaderboardSectionExpanded,
    openWorkspaceForSession,
    openDashboardForSession,
    deleteSession,
    themeMode,
    isOnline: openRouterGraph.isOnline,
    openRouterAccessAllowed,
    isCurrentProfileAdmin,
    syncConfig,
    pendingSyncSummary,
    sessionQuotaStatus,
    navigateAppRoute,
    openAdaptiveWorkspaceFromHeader,
    showAdminWorkspace,
    showOpenRouterWorkspace,
    setThemeMode,
    signOut,
    authLoading,
    authView,
    authSession,
    appProfileError,
    localStorageReadyForEffectiveProfile,
    supabaseInitialSyncPending,
    effectiveProfileId,
    authEmail,
    authPassword,
    authNewPassword,
    authNewPasswordConfirm,
    authBusy,
    authMessage,
    authMessageTone,
    authError,
    perfDiagnosticsEnabled,
    signInWithSupabase,
    requestSupabasePasswordReset,
    updateSupabasePassword,
    showAuthView,
    setAuthEmail,
    setAuthPassword,
    setAuthNewPassword,
    setAuthNewPasswordConfirm,
    sessionCreationSource,
    sessionCreationName,
    dictationScriptJson,
    dictationScriptValidation,
    changeSessionCreationSource,
    setSessionCreationName,
    createSessionWithMode,
    changeDictationScriptJson,
    validateScriptImport,
    createSessionFromDictationScript,
    cancelSessionCreation,
    insightsCollapsed,
    metricsRangeView,
    trend,
    insightsDiagnosticMessage,
    insightsDiagnosticFallbackReport,
    workspaceMode,
    ttsCurrentChunk,
    ttsPacingMode,
    ttsStatus,
    lastSessionForLanguage,
    lastSessionScoreHelpText,
    languageTodaySummary,
    setMetricsLanguageView,
    setMetricsRangeView,
    setInsightsDiagnosticInputMode,
    setInsightsCollapsed,
    localDevFeaturesAvailable,
  });

  return {
    appRouteRendererProps: {
      syncAuthRequired: syncConfig.authRequired,
      authLoading,
      authView,
      authSession,
      appProfile,
      appProfileError,
      localStorageReadyForEffectiveProfile,
      supabaseInitialSyncPending,
      authWorkspaceProps: routeCompositionRuntime.authWorkspaceProps,
      isFocusedTrainingRoute: routeCompositionRuntime.isFocusedTrainingRoute,
      themeMode,
      dictaLanguageView,
      setDictaLanguageView,
      navigateAppRoute,
      focusedTrainingProps,
      perfDiagnosticsEnabled,
      appShellHeaderProps: routeCompositionRuntime.appShellHeaderProps,
      sessionCreationMode,
      sessionCreateCardProps: routeCompositionRuntime.sessionCreateCardProps,
      pendingSessions,
      activeSessionId,
      openWorkspaceForSession,
      deleteSession,
      workspaceMode,
      dashboardSession,
      sessions,
      formatSessionStatus,
      formatSessionDate,
      formatSessionPlaybackDuration,
      showLeaderboardWorkspace,
      adaptiveAdvancedDiagnosticsProps: routeCompositionRuntime.adaptiveAdvancedDiagnosticsProps,
      adaptiveBenchmarkSectionProps: routeCompositionRuntime.adaptiveBenchmarkSectionProps,
      openRouterAccessState,
      openRouterAccessMessage,
      openRouterWorkspaceProps: routeCompositionRuntime.openRouterWorkspaceProps,
      canAccessAdminWorkspace: openRouterGraph.allowCustomSessionGeneration,
      adminWorkspaceProps: routeCompositionRuntime.adminWorkspaceProps,
      leaderboardWorkspaceProps: routeCompositionRuntime.leaderboardWorkspaceProps,
      liveMetricsDockProps: routeCompositionRuntime.liveMetricsDockProps,
    },
  };
}

export type DictaRuntimeRootPresentationGraph = ReturnType<typeof useDictaRuntimeRootPresentationGraph>;
