import { useMemo } from 'react';
import type { SessionCreateCardProps } from '../components/runtime-workspaces/SessionCreateCard';

export function useSessionCreateCardProps({
  sessionCreationSource,
  sessionCreationName,
  sessionQuotaStatus,
  canCreateSessionFromDialog,
  localDevFeaturesAvailable,
  dictationScriptJson,
  dictationScriptValidation,
  validatedDictationScript,
  onSessionCreationSourceChange,
  onSessionCreationNameChange,
  onCreateSessionWithMode,
  onDictationScriptJsonChange,
  onValidateScriptImport,
  onCreateSessionFromDictationScript,
  onCancel,
  MetricComponent,
}: SessionCreateCardProps): SessionCreateCardProps {
  return useMemo(() => ({
    sessionCreationSource,
    sessionCreationName,
    sessionQuotaStatus,
    canCreateSessionFromDialog,
    localDevFeaturesAvailable,
    dictationScriptJson,
    dictationScriptValidation,
    validatedDictationScript,
    onSessionCreationSourceChange,
    onSessionCreationNameChange,
    onCreateSessionWithMode,
    onDictationScriptJsonChange,
    onValidateScriptImport,
    onCreateSessionFromDictationScript,
    onCancel,
    MetricComponent,
  }), [
    sessionCreationSource,
    sessionCreationName,
    sessionQuotaStatus,
    canCreateSessionFromDialog,
    localDevFeaturesAvailable,
    dictationScriptJson,
    dictationScriptValidation,
    validatedDictationScript,
    onSessionCreationSourceChange,
    onSessionCreationNameChange,
    onCreateSessionWithMode,
    onDictationScriptJsonChange,
    onValidateScriptImport,
    onCreateSessionFromDictationScript,
    onCancel,
    MetricComponent,
  ]);
}
