import { useOpenRouterWorkspaceProps } from './useOpenRouterWorkspaceProps';
import { useAdminWorkspaceProps } from './useAdminWorkspaceProps';
import type { UseWorkspacePanelPropsRuntimeArgs } from './useWorkspacePanelPropsRuntimeTypes';

export type { UseWorkspacePanelPropsRuntimeArgs } from './useWorkspacePanelPropsRuntimeTypes';

export function useWorkspacePanelPropsRuntime({
  effectiveOpenRouterDefaultModel,
  assignedOpenRouterModel,
  getAuthHeaders,
  setOpenRouterDefaultModel,
  openRouterModels,
  openRouterStatus,
  openRouterError,
  refreshOpenRouterModels,
  showLeaderboardWorkspace,
  showAdminWorkspace,
  showOpenRouterWorkspace,

  adaptiveBenchmarksByInputLanguage,
  adaptiveSessionFeedbackByInputLanguage,
  selectedBenchmarkInputMode,
  selectedBenchmarkLanguage,
  openRouterGenerateFocusRequest,
  activeOpenRouterJobs,
  openRouterJobNotifications,
  trainingGenerationNowMs,
  trackOpenRouterJob,
  createOpenRouterErrorSession,

  adminSessions,
  adminStorageSummary,
  adminFileInventory,
  adminFileInventoryError,
  exportMessage,
  supabaseSyncStatus,
  adminLanguageView,
  setAdminLanguageView,
  importDictaLocalStorageSnapshot,
  appProfile,
  visibleProfiles,
  adminProfileSessionCounts,
  adminProfileFilter,
  setAdminProfileFilter,
  updateAdminProfileAccess,
  adminRemoteStatus,
  setExportMessage,
}: UseWorkspacePanelPropsRuntimeArgs) {
  const openRouterWorkspaceProps = useOpenRouterWorkspaceProps({
    defaultModel: effectiveOpenRouterDefaultModel,
    assignedModel: assignedOpenRouterModel,
    getAuthHeaders,
    setOpenRouterDefaultModel,
    models: openRouterModels,
    status: openRouterStatus,
    error: openRouterError,
    onRefreshModels: refreshOpenRouterModels,
    onBackToTraining: showLeaderboardWorkspace,
    benchmarks: adaptiveBenchmarksByInputLanguage,
    sessionFeedbackByInputLanguage: adaptiveSessionFeedbackByInputLanguage,
    defaultGenerateInputMode: selectedBenchmarkInputMode,
    defaultGenerateLanguage: selectedBenchmarkLanguage,
    focusGenerateRequest: openRouterGenerateFocusRequest,
    activeJobs: activeOpenRouterJobs,
    jobNotifications: openRouterJobNotifications,
    generationNowMs: trainingGenerationNowMs,
    onTrackJob: trackOpenRouterJob,
    onCreateGenerationErrorSession: createOpenRouterErrorSession,
  });

  const adminWorkspaceProps = useAdminWorkspaceProps({
    sessions: adminSessions,
    summary: adminStorageSummary,
    fileInventory: adminFileInventory,
    fileInventoryError: adminFileInventoryError,
    exportMessage,
    syncStatus: supabaseSyncStatus,
    languageView: adminLanguageView,
    onChangeLanguage: setAdminLanguageView,
    onBackToTraining: showLeaderboardWorkspace,
    onOpenOverview: showAdminWorkspace,
    onOpenOpenRouter: showOpenRouterWorkspace,
    onImportLocalStorage: importDictaLocalStorageSnapshot,
    appProfile,
    visibleProfiles,
    profileSessionCounts: adminProfileSessionCounts,
    selectedProfileFilter: adminProfileFilter,
    onChangeProfileFilter: setAdminProfileFilter,
    onUpdateProfileAccess: updateAdminProfileAccess,
    getAuthHeaders,
    remoteAdminStatus: adminRemoteStatus,
    openRouterModels,
    openRouterModelStatus: openRouterStatus,
    openRouterModelError: openRouterError,
    onRefreshOpenRouterModels: refreshOpenRouterModels,
    setExportMessage,
  });

  return {
    openRouterWorkspaceProps,
    adminWorkspaceProps,
  };
}
