import { useOpenRouterWorkspaceProps } from './useOpenRouterWorkspaceProps';
import { useAdminWorkspaceProps } from './useAdminWorkspaceProps';
import type { UseWorkspacePanelPropsRuntimeArgs } from './useWorkspacePanelPropsRuntimeTypes';

export type { UseWorkspacePanelPropsRuntimeArgs } from './useWorkspacePanelPropsRuntimeTypes';

export function useWorkspacePanelPropsRuntime({
  effectiveOpenRouterDefaultModel,
  assignedOpenRouterModel,
  getAuthHeaders,
  setOpenRouterDefaultModel,
  openRouterModels,
  openRouterStatus,
  openRouterError,
  refreshOpenRouterModels,
  showLeaderboardWorkspace,

  selectedBenchmarkProfile,
  selectedSessionFeedback,
  getBenchmarkActiveSessionStatus,
  adaptiveBenchmarksByInputLanguage,
  adaptiveSessionFeedbackByInputLanguage,
  setSelectedBenchmarkInputMode,
  setSelectedBenchmarkLanguage,
  setBenchmarkExportMessage,
  setSessionFeedbackMessage,
  selectedBenchmarkInputMode,
  selectedBenchmarkLanguage,
  openRouterGenerateFocusRequest,
  activeOpenRouterJobs,
  openRouterJobNotifications,
  trainingGenerationNowMs,
  trackOpenRouterJob,
  createOpenRouterErrorSession,
  copySelectedBenchmarkJson,
  downloadSelectedBenchmarkJson,
  copyBenchmarkWithDictationScriptPrompt,
  copyBenchmarkFeedbackPrompt,
  copyBenchmarkFeedbackJson,
  copySessionFeedbackJson,
  copyDictationScriptPrompt,
  copyDictationScriptTemplate,
  copyBenchmarkFeedbackPromptWithHumanFeedback,

  adminSessions,
  adminStorageSummary,
  adminFileInventory,
  adminFileInventoryError,
  exportMessage,
  supabaseSyncStatus,
  adminLanguageView,
  setAdminLanguageView,
  importDictaLocalStorageSnapshot,
  appProfile,
  visibleProfiles,
  adminProfileSessionCounts,
  adminProfileFilter,
  setAdminProfileFilter,
  updateAdminProfileAccess,
  adminRemoteStatus,
  setExportMessage,
}: UseWorkspacePanelPropsRuntimeArgs) {
  const openRouterWorkspaceProps = useOpenRouterWorkspaceProps({
    defaultModel: effectiveOpenRouterDefaultModel,
    assignedModel: assignedOpenRouterModel,
    getAuthHeaders,
    setOpenRouterDefaultModel,
    models: openRouterModels,
    status: openRouterStatus,
    error: openRouterError,
    onRefreshModels: refreshOpenRouterModels,
    onBackToTraining: showLeaderboardWorkspace,
    exportProfile: selectedBenchmarkProfile,
    exportSessionFeedback: selectedSessionFeedback,
    getBenchmarkActiveSessionStatus,
    benchmarks: adaptiveBenchmarksByInputLanguage,
    sessionFeedbackByInputLanguage: adaptiveSessionFeedbackByInputLanguage,
    setSelectedBenchmarkInputMode,
    setSelectedBenchmarkLanguage,
    setBenchmarkExportMessage,
    setSessionFeedbackMessage,
    defaultGenerateInputMode: selectedBenchmarkInputMode,
    defaultGenerateLanguage: selectedBenchmarkLanguage,
    focusGenerateRequest: openRouterGenerateFocusRequest,
    activeJobs: activeOpenRouterJobs,
    jobNotifications: openRouterJobNotifications,
    generationNowMs: trainingGenerationNowMs,
    onTrackJob: trackOpenRouterJob,
    onCreateGenerationErrorSession: createOpenRouterErrorSession,
    onCopyBenchmark: (profile) => void copySelectedBenchmarkJson(profile),
    onExportBenchmark: (profile) => downloadSelectedBenchmarkJson(profile),
    onCopyBenchmarkWithScriptPrompt: (profile) => void copyBenchmarkWithDictationScriptPrompt(profile),
    onCopyBenchmarkFeedbackPrompt: (profile, feedback) => void copyBenchmarkFeedbackPrompt(profile, feedback),
    onCopyBenchmarkFeedback: (profile, feedback) => void copyBenchmarkFeedbackJson(profile, feedback),
    onCopySessionFeedback: (profile, feedback) => void copySessionFeedbackJson(profile, feedback),
    onCopyScriptPrompt: (profile) => void copyDictationScriptPrompt(profile),
    onCopyScriptTemplate: (profile) => void copyDictationScriptTemplate(profile),
    onCopyBenchmarkFeedbackPromptWithHumanFeedback: (profile, feedback, humanFeedback) =>
      void copyBenchmarkFeedbackPromptWithHumanFeedback(profile, feedback, humanFeedback),
  });

  const adminWorkspaceProps = useAdminWorkspaceProps({
    sessions: adminSessions,
    summary: adminStorageSummary,
    fileInventory: adminFileInventory,
    fileInventoryError: adminFileInventoryError,
    exportMessage,
    syncStatus: supabaseSyncStatus,
    languageView: adminLanguageView,
    onChangeLanguage: setAdminLanguageView,
    onBackToTraining: showLeaderboardWorkspace,
    onImportLocalStorage: importDictaLocalStorageSnapshot,
    appProfile,
    visibleProfiles,
    profileSessionCounts: adminProfileSessionCounts,
    selectedProfileFilter: adminProfileFilter,
    onChangeProfileFilter: setAdminProfileFilter,
    onUpdateProfileAccess: updateAdminProfileAccess,
    getAuthHeaders,
    remoteAdminStatus: adminRemoteStatus,
    openRouterModels,
    openRouterModelStatus: openRouterStatus,
    openRouterModelError: openRouterError,
    onRefreshOpenRouterModels: refreshOpenRouterModels,
    setExportMessage,
  });

  return {
    openRouterWorkspaceProps,
    adminWorkspaceProps,
  };
}
