import type {
  BrowserPlaybackDelegateArgs,
  BuildSemanticPhrasesForCurrentSession,
  UseTtsSessionOrchestrationRuntimeArgs,
} from '../ttsSessionOrchestrationDelegateTypes';

export function buildTtsSessionBrowserPlaybackArgs(
  args: UseTtsSessionOrchestrationRuntimeArgs,
  buildSemanticPhrasesForCurrentSession: BuildSemanticPhrasesForCurrentSession,
): BrowserPlaybackDelegateArgs {
  return {
    activeSessionFinished: args.activeSessionFinished,
    activeSession: args.activeSession,
    ttsStatus: args.ttsStatus,
    ttsText: args.ttsText,
    ttsLanguage: args.ttsLanguage,
    ttsPacingMode: args.ttsPacingMode,
    ttsSpeechRate: args.ttsSpeechRate,
    ttsTranscript: args.ttsTranscript,
    browserTtsVoices: args.browserTtsVoices,
    ttsPlaybackProfile: args.ttsPlaybackProfile,
    browserTtsSafePauseGateSettings: args.browserTtsSafePauseGateSettings,
    perfDiagnostics: args.perfDiagnostics,
    stopTtsPlaybackRef: args.stopTtsPlaybackRef,
    ttsPausedAtWordIndexRef: args.ttsPausedAtWordIndexRef,
    ttsCompletedSourceWordsRef: args.ttsCompletedSourceWordsRef,
    ttsStartedAtMsRef: args.ttsStartedAtMsRef,
    ttsLagOutlierCountRef: args.ttsLagOutlierCountRef,
    ttsLastValidControlLagSecRef: args.ttsLastValidControlLagSecRef,
    ttsUnsafeChunkCountRef: args.ttsUnsafeChunkCountRef,
    ttsChunkAccuracyWindowRef: args.ttsChunkAccuracyWindowRef,
    ttsLastAccuracySnapshotRef: args.ttsLastAccuracySnapshotRef,
    ttsLastControllerActionRef: args.ttsLastControllerActionRef,
    ttsLiveSignalRef: args.ttsLiveSignalRef,
    ttsPracticeLiveTextRef: args.ttsPracticeLiveTextRef,
    ttsUtteranceRef: args.ttsUtteranceRef,
    ttsChunkStartMsRef: args.ttsChunkStartMsRef,
    ttsChunkStartWordIndexRef: args.ttsChunkStartWordIndexRef,
    ttsChunkWordCountRef: args.ttsChunkWordCountRef,
    ttsSemanticPhraseAdvanceCountRef: args.ttsSemanticPhraseAdvanceCountRef,
    ttsSemanticPhraseReplayCountRef: args.ttsSemanticPhraseReplayCountRef,
    buildSemanticPhrasesForCurrentSession,
    isBrowserTtsSupported: args.isBrowserTtsSupported,
    speakBrowserTts: args.speakBrowserTts,
    resolveActiveBrowserTtsVoice: args.resolveActiveBrowserTtsVoice,
    collectBrowserTtsEnvironmentForSession: args.collectBrowserTtsEnvironmentForSession,
    getHistoricalPerformanceProfile: args.getHistoricalPerformanceProfile,
    getBenchmarkSnapshot: args.getBenchmarkSnapshot,
    getAdaptiveController: args.getAdaptiveController,
    beginAdaptiveSessionFeedback: args.beginAdaptiveSessionFeedback,
    recordPhrasePlaybackEvent: args.recordPhrasePlaybackEvent,
    recordAdaptiveBenchmark: args.recordAdaptiveBenchmark,
    setAdaptiveSemanticDebug: args.setAdaptiveSemanticDebug,
    setTtsCurrentChunk: args.setTtsCurrentChunk,
    setTtsPacingMode: args.setTtsPacingMode,
    setTtsSpeechRate: args.setTtsSpeechRate,
    setTtsStatus: args.setTtsStatus,
    setRunning: args.setRunning,
    setSessionStatus: args.setSessionStatus,
    setError: args.setError,
  };
}
