import { vi } from 'vitest';
import type { UseFocusedTrainingRouteRuntimeArgs } from '../../src/app/useFocusedTrainingRouteRuntime';
import { BROWSER_TTS_SESSION_INPUT_MODE } from '../../src/core/sessionInputModes';
import { createFocusedTrainingSession } from './focusedTrainingRouteRuntimeSessionFactory';

export function createFocusedTrainingRouteRuntimeArgs(
  overrides: Partial<UseFocusedTrainingRouteRuntimeArgs> = {},
): UseFocusedTrainingRouteRuntimeArgs {
  const activeSession = createFocusedTrainingSession();

  return {
    activeInputMode: BROWSER_TTS_SESSION_INPUT_MODE,
    activeSession,
    activeTrainingSubmissionMeta: null,
    activeInputLabel: 'Input # 2 - Text to Speech (TTS)',
    sessionStatus: 'ready',
    ttsStatus: 'ready',
    running: false,
    inputSettingsLocked: false,
    activeVisibleScore: 91,
    activeLiveScoreHelpText: 'score help',
    activeLivePointsLabel: '9/10 pts',
    activeLivePointsHelpText: 'points help',
    activeVisibleAccuracy: 97.5,
    activeLiveAccuracyHelpText: 'accuracy help',
    lagSec: 0.33,
    activeSessionFinished: false,
    ttsHasText: true,
    error: '',
    trainingSubmitMessage: '',
    exportMessage: '',
    openRouterJobStatus: '',
    openRouterError: '',
    ttsTranscript: {
      words: [
        { word: 'eins', start: 0, end: 1 },
        { word: 'zwei', start: 1, end: 2 },
        { word: 'drei', start: 2, end: 3 },
        { word: 'vier', start: 3, end: 4 },
      ],
    },
    estimateTtsSpokenWordIndex: vi.fn(() => 2),
    ttsSpeechRate: 1,
    ttsLanguage: 'de',
    adaptiveSemanticDebug: {
      semanticCutPenalty: 0,
      unsafePauseCount: 0,
      safePauseCount: 0,
      deferredPauseCount: 0,
      replayDeniedByBoundaryCount: 0,
      averageSemanticCompleteness: 1,
      averagePhraseDifficulty: 0,
      inputExecutionFidelityScore: 1,
      currentPhraseIndex: 0,
      currentPhraseId: '',
      currentPhraseTextPreview: '',
      totalSemanticPhrases: 0,
      phraseAdvanceCount: 0,
      phraseReplayCount: 0,
      lastPhraseAdvanceReason: '',
    },
    ttsPracticeText: 'typed text',
    ttsPlayerProgressTick: 0,
    seekTtsPlayback: vi.fn(),
    resetSession: vi.fn(),
    playTts: vi.fn(),
    resumeTts: vi.fn(),
    pauseTts: vi.fn(),
    stopTtsPlayback: vi.fn(),
    punctuateTtsPracticeText: vi.fn((value?: string) => value ?? ''),
    onTtsPracticeChange: vi.fn(),
    onTtsPracticeKeyDown: vi.fn(),
    submitTtsSession: vi.fn(),
    setInputSettingsLocked: vi.fn(),
    setError: vi.fn(),
    setExportMessage: vi.fn(),
    telemetryRef: { current: null },
    ttsStartedAtMsRef: { current: null },
    ttsPracticeLiveTextRef: { current: 'typed text' },
    ttsPracticeLastInputAtMsRef: { current: 0 },
    pendingSessions: [],
    activeSessionId: activeSession.id,
    openWorkspaceForSession: vi.fn(),
    deleteSession: vi.fn(),
    supabaseSyncStatus: {
      enabled: false,
      state: 'disabled',
      message: '',
      lastSyncedAt: null,
      imported: 0,
      pushed: 0,
    },
    pendingSyncSummary: {
      count: 0,
      hasPending: false,
    },
    openRouterAccessAllowed: true,
    isOnline: true,
    effectiveOpenRouterDefaultModel: 'test-model',
    sessionQuotaStatus: {
      blocked: false,
      message: '',
    },
    openRouterOfflineTitle: '',
    activeOpenRouterJobs: [],
    openRouterJobNotifications: {},
    trainingGenerationNotices: {},
    trainingGenerationNowMs: 0,
    cancelOpenRouterJob: vi.fn(),
    adaptiveOpenRouterBusy: false,
    topicOpenRouterBusy: false,
    directGenerationDurationMinutes: 3,
    generateAdaptiveNextSessionFromOpenRouter: vi.fn(),
    generateTopicNextSessionFromOpenRouter: vi.fn(),
    ...overrides,
  };
}
